export const jokes = [
    { setup: "Why don't scientists trust atoms?", punchline: "Because they make up everything!" },
    { setup: "What do you call fake spaghetti?", punchline: "An impasta!" },
    { setup: "Why did the scarecrow win an award?", punchline: "Because he was outstanding in his field!" },
    { setup: "Why don't skeletons fight each other?", punchline: "They don't have the guts." },
    { setup: "What did one ocean say to the other ocean?", punchline: "Nothing, they just waved." },
    { setup: "Why do cows have hooves instead of feet?", punchline: "Because they lactose." },
    { setup: "Why did the bicycle fall over?", punchline: "Because it was two-tired!" },
    { setup: "What did the grape do when it got stepped on?", punchline: "Nothing, it just let out a little wine!" },
    { setup: "Why was the math book sad?", punchline: "It had too many problems." },
    { setup: "What do you call cheese that isn't yours?", punchline: "Nacho cheese!" },
    { setup: "Why did the golfer bring two pairs of pants?", punchline: "In case he got a hole in one." },
    { setup: "What did the buffalo say to his son when he left?", punchline: "Bison." },
    { setup: "Why can't your nose be 12 inches long?", punchline: "Because then it would be a foot." },
    { setup: "What does a cloud wear under his raincoat?", punchline: "Thunderwear." },
    { setup: "Why did the chicken go to the seance?", punchline: "To talk to the other side." },
    { setup: "What kind of shoes do ninjas wear?", punchline: "Sneakers." },
    { setup: "Why did the coffee file a police report?", punchline: "It got mugged." },
    { setup: "What did the janitor say when he jumped out of the closet?", punchline: "Supplies!" },
    { setup: "Why do seagulls fly over the sea?", punchline: "Because if they flew over the bay, they’d be bagels." },
    { setup: "How does a penguin build its house?", punchline: "Igloos it together." },
    { setup: "What do you call a bear with no teeth?", punchline: "A gummy bear." },
    { setup: "Why don't some couples go to the gym?", punchline: "Because some relationships don’t work out." },
    { setup: "Why did the mushroom go to the party alone?", punchline: "Because he's a fungi." },
    { setup: "How do you organize a space party?", punchline: "You planet." },
    { setup: "Why was the big cat disqualified from the race?", punchline: "Because it was a cheetah." },
    { setup: "Why are ghosts bad at lying?", punchline: "Because they are too transparent." },
    { setup: "What do you call an alligator in a vest?", punchline: "An investigator." },
    { setup: "Why did the tomato turn red?", punchline: "Because it saw the salad dressing." },
    { setup: "What’s orange and sounds like a parrot?", punchline: "A carrot." },
    { setup: "What did the dog say to the tree?", punchline: "Bark." },
    { setup: "Why are fish so smart?", punchline: "Because they live in schools." },
    { setup: "How do you make a tissue dance?", punchline: "Put a little boogie in it." },
    { setup: "What did the duck say when it bought lipstick?", punchline: "Put it on my bill." },
    { setup: "Why did the math teacher break up with the geometry teacher?", punchline: "Because they lacked chemistry." },
    { setup: "Why was the belt arrested?", punchline: "For holding up a pair of pants." },
    { setup: "Why did the man put his money in the blender?", punchline: "Because he wanted to make some cold hard cash." },
    { setup: "What did the zero say to the eight?", punchline: "Nice belt!" },
    { setup: "How does a snowman get around?", punchline: "By riding an ‘icicle." },
    { setup: "Why did the golfer bring an extra pair of socks?", punchline: "In case he gets a hole in one." },
    { setup: "What did the fish say when it hit the wall?", punchline: "Dam!" },
    { setup: "Why are frogs so happy?", punchline: "They eat whatever bugs them!" },
    { setup: "Why did the baker go to therapy?", punchline: "He kneaded help." },
    { setup: "What do you call a bee that can’t make up its mind?", punchline: "A maybe." },
    { setup: "Why don’t eggs tell jokes?", punchline: "They’d crack each other up." },
    { setup: "Why do melons have weddings?", punchline: "Because they cantaloupe." },
    { setup: "How do you catch a whole school of fish?", punchline: "With bookworms." },
    { setup: "Why did the invisible man turn down the job offer?", punchline: "He couldn’t see himself doing it." },
    { setup: "Why did the computer go to the doctor?", punchline: "It had a virus." },
    { setup: "What’s brown and sticky?", punchline: "A stick." },
    { setup: "Why did the photo go to jail?", punchline: "It was framed." },
    { setup: "Why can’t a bicycle stand on its own?", punchline: "Because it’s two-tired." }
];

// module.exports = { jokes };